version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static  # Том для статических файлов
      - .:/app  # Ваш проект
    environment:
      - DEBUG=1  # Убедитесь, что debug включен для разработки
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
