# Generated by Django 5.1.2 on 2025-01-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_health', models.IntegerField(default=100)),
                ('base_mana', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='game.item'),
        ),
        migrations.AlterField(
            model_name='characterquest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_quests', to='game.quest'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.characterclass'),
        ),
    ]
